# Generated by Django 6.0.2 on 2026-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobRole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='full_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
