# Generated by Django 6.0.2 on 2026-03-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobRole', '0002_jobrole_full_text'),
        ('Recruiter', '0002_recruiter_is_verified_alter_recruiter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='Recruiter.recruiter'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='required_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
