# Generated by Django 6.0.2 on 2026-02-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Interview.interviewsession'),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='total_score',
            field=models.FloatField(editable=False),
        ),
    ]
