# Generated by Django 6.0.2 on 2026-03-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
        ('JobRole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobRole.jobrole'),
        ),
    ]
