# Generated by Django 6.0.2 on 2026-03-02 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be alphanumeric or contain underscores.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
