# Generated by Django 6.0.2 on 2026-03-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
    ]
