# Generated by Django 6.0.2 on 2026-03-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_alter_interviewsession_job_role'),
        ('Resume', '0001_initial'),
        ('candidate', '0003_remove_candidate_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRole',
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidate.candidate'),
        ),
    ]
