# Generated by Django 6.0.2 on 2026-02-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
