# Generated by Django 6.0.2 on 2026-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0002_recruiter_is_verified_alter_recruiter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
